server.port=8081

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/payroute
spring.datasource.username=payroute
spring.datasource.password=Vatsvinu

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR

# JWT Configuration
jwt.secret=afhs34w5y5hrewg4et35hy456w3456rtyfght76ertsdfx
jwt.expiration=86400000

# Internal service-to-service auth
internal.service-token=payroute-internal-service-token