server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/payroute
spring.datasource.username=payroute
spring.datasource.password=Vatsvinu
spring.jpa.hibernate.ddl-auto=update
jwt.secret=afhs34w5y5hrewg4et35hy456w3456rtyfght76ertsdfx
jwt.expiration=86400000

# Internal service-to-service auth
auth.service.base-url=http://localhost:8081
auth.service.internal-token=payroute-internal-service-token