server.port=8082

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/payroute
spring.datasource.username=payroute
spring.datasource.password=Vatsvinu

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=afhs34w5y5hrewg4et35hy456w3456rtyfght76ertsdfx
jwt.expiration=86400000